#requires 'perl', '5.24.1';

# framework
requires 'Dancer2' => '0.205001';

requires 'Starman';

# basics
requires 'YAML';
requires 'URL::Encode::XS';
requires 'CGI::Deurl::XS';
requires 'HTTP::Parser::XS';
requires 'Plack::Middleware::Deflater';
requires 'Plack';
requires 'Config::General';
requires 'Data::UUID';
requires 'JSON::XS';
requires 'Data::Printer';
requires 'List::Compare';
requires 'Data::Validate::UUID';

# logging
requires 'Log::Any';
requires 'Log::Any::Adapter::Screen';
requires 'Log::Report';

# database
requires 'DBD::Pg';
requires 'DateTime::Format::Pg';
requires 'DBIx::Class';
requires 'DBIx::Class::Schema::Loader';
requires 'DBIx::Class::TimeStamp';

# dancer plugin
requires 'Dancer2::Plugin::Auth::Tiny';
requires 'Dancer2::Plugin::DBIC';
requires 'Dancer2::Logger::LogAny';
requires 'Dancer2::Plugin::Passphrase';
requires 'Dancer2::Plugin::REST';
requires 'Dancer2::Plugin::REST';
requires 'Dancer2::Session::YAML';

# moose
requires 'Moose';
requires 'MooseX::Constructor::AllErrors';
requires 'MooseX::Types::UUID';
requires 'MooseX::Storage';
requires 'MooseX::MarkAsMethods';
requires 'MooseX::NonMoose';

on 'test' => sub {
    requires 'Test::More';
    requires 'HTTP::Request::Common';
};
