requires 'perl', '5.26.0';


# basics
requires 'Data::UUID';
requires 'Data::Printer';
requires 'DateTime::Format::Strptime';
requires 'List::Compare';
requires 'Mail::Sendmail';
requires 'aliased';
requires 'Try::Tiny';
requires 'Class::StrongSingleton';
requires 'Time::HiRes';
requires 'Time::Moment', ">= 0.43";
requires 'IO::Socket::SSL';
requires 'Submodules';


# mojolicious
requires 'Minion';
requires 'Mojolicious', '7.87';	# for Mojo::JSON's bootstrapping of Cpanel::JSON::XS
requires 'Cpanel::JSON::XS';
requires 'Mojo::Pg';
requires 'Mojo::Server::PSGI';
requires 'Mojo::JWT';
requires 'Mojolicious::Plugin::Bcrypt';
requires 'Mojolicious::Plugin::Util::RandomString';
requires 'Mojolicious::Plugin::NYTProf';

requires 'Moo';
requires 'Moo::Role::ToJSON';
requires 'Type::Tiny';
requires 'Types::Standard';
requires 'Types::UUID';
requires 'Role::Tiny';
requires 'List::MoreUtils';
requires 'List::MoreUtils::XS';

### Legacy Deps
#
# String::CamelCase 0.03 had a broken META file that prevents the toolchain
# from being able to figure out its version, thus breaking 'carton install
# --deployment'. The issue was resolved in 0.04
# All our dependencies rely on 0.02 and up, but just to be careful, we'll pin
# it at 0.04 or greater.
requires 'String::CamelCase', '>= 0.04';

# database
requires 'DBD::Pg';
requires 'DBIx::Class';
requires 'DBIx::Class::Schema::Loader';
requires 'DBIx::Class::Helpers';
# DateTime::Format::Pg is required for DBIx::Class to inflate DateTimes, and
# can be removed once DBIx::Class is removed
requires 'DateTime::Format::Pg';
requires 'Config::General';
requires 'DBIx::Class::TimeStamp';

# moose
requires 'Moose' => '2.1400';
requires 'MooseX::NonMoose';

# logging
requires 'Log::Any';
requires 'Log::Any::Adapter::Log4perl';
requires 'Log::Any::Adapter::Screen';
requires 'Log::Log4perl';
requires 'Log::Log4perl::Layout::JSON';
requires 'Log::Report';


on 'test' => sub {
    requires 'Test::More';
    requires 'Test::Exception';
    requires 'Mock::Quick';
    requires 'Test::PostgreSQL', ">= 1.24";
    requires 'Test::Pod::Coverage';
    requires 'IO::All';
    requires 'JSON::Validator';
    requires 'YAML::XS';
};

# note: DBD::Pg will fail to install on macos 10.13.x because Apple is
# shipping a bad berkeley-db. To fix (do this in a subshell you will close
# afterward, so as to not pollute your environment):
# eval $(perl -Mlocal::lib='local/lib/perl5')
# cpanm --look DB_File
# (you're now in another subshell)
# edit config.in to add these two lines, replacing the existing INCLUDE and LIB lines:
#   INCLUDE	= /opt/local/include/db48
#   LIB	= /opt/local/lib/db48
# perl Makefile.PL; make install
# <close subshell>
# see also: https://rt.cpan.org/Public/Bug/Display.html?id=125238
# and https://rt.perl.org/Ticket/Display.html?id=133280
