package Conch::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Conch::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=preflight;port=5432',
        user => 'preflight',
        password => 'bs9BsWn68U8O',
        quote_names => q{1},
    }
);

=head1 NAME

Conch::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Conch>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Conch::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Super-User

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
