#!/bin/bash

export PATH=$PATH:/opt/local/bin:/opt/local/sbin:/opt/local/lib/perl5/site_perl/bin
cd /opt/conch

case "$1" in
  start)
    carton exec hypnotoad bin/conch
    ;;
  stop)
    carton exec hypnotoad -s bin/conch
    ;;
  restart)
    carton exec hypnotoad bin/conch
    ;;
  *)
    echo "Usage:  {start|stop|restart}"
    exit 1
    ;;
esac
