use strict;
use warnings;
use Test::More;

# This test is based upon content generated by Dist::Zilla::Plugin::Test::PodSpelling 2.007005
use Test::Requires 'Test::Spelling' => 0.12;
use Pod::Wordlist;
use YAML::XS;
use Conch::Plugin::JsonValidator;

foreach my $file (
    Conch::Plugin::JsonValidator::OUTPUT_SCHEMA_FILE,
    Conch::Plugin::JsonValidator::INPUT_SCHEMA_FILE,
) {
    my $data = YAML::XS::LoadFile($file);
    add_stopwords(keys $data->{definitions}->%*);
}

add_stopwords(<DATA>);

all_pod_files_spelling_ok(qw(lib t misc));

__DATA__
ANDed
api
auth
az
bunyan
chainable
circ
Circonus
csv
datacenter
datacenters
deduplication
dsn
filepath
hba
ipmi
ISO
iso8601
Joyent
jsonb
JWT
listref
Mojo
Mojolicious
MPL
mtu
nullable
ORed
postgres
PROXYED
pxe
rebless
rels
renderer
resultset
resultsets
rfc
ro
Rollbar
schema
schemas
sku
subref
subselect
subtest
subworkspace
timestamptz
TODO
validator
VLAN
workspace
workspaces
