use strict;
use warnings;
use Test::More;
use Test::Warnings;

# This test is based upon content generated by Dist::Zilla::Plugin::Test::PodSpelling 2.007005
use Test::Spelling 0.12;
use Pod::Wordlist;
use YAML::XS;

foreach my $file (glob('json-schema/*.yaml')) {
    my $data = YAML::XS::LoadFile($file);
    add_stopwords(keys $data->{'$defs'}->%*);
}

add_stopwords(<DATA>);

subtest all_pod_files_spelling_ok => sub {
    all_pod_files_spelling_ok(qw(lib t misc));
};

done_testing;

__DATA__
ANDed
api
auth
az
bunyan
chainable
circ
Circonus
csv
datacenter
datacenters
deduplication
dsn
filepath
hba
iff
ipmi
ISO
iso8601
Joyent
jsonb
JWT
listref
Mojo
Mojolicious
MPL
mtu
nullable
ORed
postgres
PROXYED
pxe
rebless
rels
renderer
resultset
resultsets
rfc
ro
Rollbar
schema
schemas
sku
subref
subselect
subtest
timestamptz
TODO
unstarted
validator
VLAN
