package Conch::Control::Device;

use strict;
use Log::Report;
use Log::Report::DBIC::Profiler;
use Dancer2::Plugin::Passphrase;

use Exporter 'import';
our @EXPORT = qw( devices_for_user );

sub devices_for_user {
  my ($schema, $user_name) = @_;

  # NOTE: 'UserDeviceAccess' is a custom package, *not* generated by dbicdump.
  # If the schema for the relations between a user and device change, this will
  # need to be updated by hand. Trying to wrangle DBIC's DSL to create the
  # correct joins was more difficult than writing the custom SQL.
  return
    $schema->resultset('UserDeviceAccess')->
      search({}, { bind => [$user_name] })->all;
};


1;
