BEGIN;


DROP TABLE IF EXISTS relay CASCADE;
DROP TABLE IF EXISTS hardware_vendor CASCADE;
DROP TABLE IF EXISTS hardware_product CASCADE;
DROP TABLE IF EXISTS datacenter CASCADE;
DROP TABLE IF EXISTS datacenter_room CASCADE;
DROP TABLE IF EXISTS datacenter_rack_role CASCADE;
DROP TABLE IF EXISTS datacenter_rack CASCADE;
DROP TABLE IF EXISTS datacenter_rack_layout CASCADE;
DROP TABLE IF EXISTS datacenter_network CASCADE;
DROP TABLE IF EXISTS datacenter_room_network CASCADE;
DROP TABLE IF EXISTS zpool_profile CASCADE;
DROP TABLE IF EXISTS zpool_attributes CASCADE;
DROP TABLE IF EXISTS hardware_product_profile CASCADE;
DROP TABLE IF EXISTS hardware_profile_settings CASCADE;
DROP TABLE IF EXISTS device CASCADE;
DROP TABLE IF EXISTS triton CASCADE;
DROP TABLE IF EXISTS triton_post_setup_stage CASCADE;
DROP TABLE IF EXISTS triton_post_setup CASCADE;
DROP TABLE IF EXISTS triton_post_setup_log CASCADE;
DROP TABLE IF EXISTS device_settings CASCADE;
DROP TABLE IF EXISTS device_location CASCADE;
DROP TABLE IF EXISTS device_environment CASCADE;
DROP TABLE IF EXISTS device_specs CASCADE;
DROP TABLE IF EXISTS device_memory CASCADE;
DROP TABLE IF EXISTS device_disk CASCADE;
DROP TABLE IF EXISTS device_nic CASCADE;
DROP TABLE IF EXISTS device_nic_state CASCADE;
DROP TABLE IF EXISTS device_neighbor CASCADE;
DROP TABLE IF EXISTS device_validate_criteria CASCADE;
DROP TABLE IF EXISTS device_report CASCADE;
DROP TABLE IF EXISTS device_validate CASCADE;
DROP TABLE IF EXISTS device_log CASCADE;
DROP TABLE IF EXISTS device_notes CASCADE;
DROP TABLE IF EXISTS user_account CASCADE;
DROP TABLE IF EXISTS user_datacenter_room_access CASCADE;

DROP EXTENSION IF EXISTS "pgcrypto" CASCADE;
DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;

COMMIT;
